import { createClient } from "@supabase/supabase-js"
import OpenAI from "openai"
import * as dotenv from "dotenv"
import * as path from "path"
import * as fs from "fs"

dotenv.config({ path: path.join(import.meta.dirname, "../../.env.local") })

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!
const OPENAI_API_KEY = process.env.OPENAI_API_KEY!

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY || !OPENAI_API_KEY) {
  console.error("Missing required environment variables:")
  if (!SUPABASE_URL) console.error("  - NEXT_PUBLIC_SUPABASE_URL")
  if (!SUPABASE_SERVICE_ROLE_KEY) console.error("  - SUPABASE_SERVICE_ROLE_KEY")
  if (!OPENAI_API_KEY) console.error("  - OPENAI_API_KEY")
  process.exit(1)
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)
const openai = new OpenAI({ apiKey: OPENAI_API_KEY })

const CURRICULUM_CODE = "CMO-97-2017"

interface TopicEntry {
  path: string
  title: string
  level: number
}

interface SubjectData {
  subject_code: string
  subject_title: string
  topics: TopicEntry[]
}

const SUBJECTS: SubjectData[] = [
  // ============================================================
  // A. MATHEMATICS
  // ============================================================
  {
    subject_code: "CALC1",
    subject_title: "Calculus 1",
    topics: [
      { path: "Functions", title: "Functions", level: 1 },
      { path: "Continuity and Limits", title: "Continuity and Limits", level: 1 },
      { path: "The Derivative", title: "The Derivative", level: 1 },
      { path: "The Slope", title: "The Slope", level: 1 },
      { path: "Rate of Change", title: "Rate of Change", level: 1 },
      { path: "The Chain Rule and the General Power Rule", title: "The Chain Rule and the General Power Rule", level: 1 },
      { path: "Implicit Differentiation", title: "Implicit Differentiation", level: 1 },
      { path: "Higher-Order Derivatives", title: "Higher-Order Derivatives", level: 1 },
      { path: "Polynomial Curves", title: "Polynomial Curves", level: 1 },
      { path: "Applications of the Derivative", title: "Applications of the Derivative", level: 1 },
      { path: "The Differential", title: "The Differential", level: 1 },
      { path: "Derivatives of Trigonometric Functions", title: "Derivatives of Trigonometric Functions", level: 1 },
      { path: "Derivative of Inverse Trigonometric Functions", title: "Derivative of Inverse Trigonometric Functions", level: 1 },
      { path: "Derivative of Logarithmic and Exponential Functions", title: "Derivative of Logarithmic and Exponential Functions", level: 1 },
      { path: "Derivative of the Hyperbolic Functions", title: "Derivative of the Hyperbolic Functions", level: 1 },
      { path: "Solutions of Equations", title: "Solutions of Equations", level: 1 },
      { path: "Transcendental Curve Tracing", title: "Transcendental Curve Tracing", level: 1 },
      { path: "Parametric Equations", title: "Parametric Equations", level: 1 },
      { path: "Partial Differentiation", title: "Partial Differentiation", level: 1 },
    ],
  },
  {
    subject_code: "CALC2",
    subject_title: "Calculus 2",
    topics: [
      { path: "Integration Concepts and Formulas", title: "Integration Concepts and Formulas", level: 1 },
      { path: "Integration Concepts and Formulas > Anti-differentiation", title: "Anti-differentiation", level: 2 },
      { path: "Integration Concepts and Formulas > Indefinite Integrals", title: "Indefinite Integrals", level: 2 },
      { path: "Integration Concepts and Formulas > Simple Power Formula", title: "Simple Power Formula", level: 2 },
      { path: "Integration Concepts and Formulas > Simple Trigonometric Functions", title: "Simple Trigonometric Functions", level: 2 },
      { path: "Integration Concepts and Formulas > Logarithmic Function", title: "Logarithmic Function", level: 2 },
      { path: "Integration Concepts and Formulas > Exponential Function", title: "Exponential Function", level: 2 },
      { path: "Integration Concepts and Formulas > Inverse Trigonometric Functions", title: "Inverse Trigonometric Functions", level: 2 },
      { path: "Integration Concepts and Formulas > Hyperbolic Functions", title: "Hyperbolic Functions (sinh u & cos u only)", level: 2 },
      { path: "Integration Concepts and Formulas > General Power Formula", title: "General Power Formula (include Substitution Rule)", level: 2 },
      { path: "Integration Concepts and Formulas > Constant of Integration", title: "Constant of Integration", level: 2 },
      { path: "Integration Concepts and Formulas > Definite Integral", title: "Definite Integral (include absolute, odd & even functions)", level: 2 },
      { path: "Integration Techniques", title: "Integration Techniques", level: 1 },
      { path: "Integration Techniques > Integration by Parts", title: "Integration by Parts", level: 2 },
      { path: "Integration Techniques > Trigonometric Integrals", title: "Trigonometric Integrals", level: 2 },
      { path: "Integration Techniques > Trigonometric Substitution", title: "Trigonometric Substitution", level: 2 },
      { path: "Integration Techniques > Rational Functions", title: "Rational Functions", level: 2 },
      { path: "Integration Techniques > Rationalizing Substitution", title: "Rationalizing Substitution", level: 2 },
      { path: "Improper Integrals", title: "Improper Integrals", level: 1 },
      { path: "Application of Definite Integral", title: "Application of Definite Integral", level: 1 },
      { path: "Application of Definite Integral > Plane Area", title: "Plane Area", level: 2 },
      { path: "Application of Definite Integral > Areas between Curves", title: "Areas between Curves", level: 2 },
      { path: "Other Applications", title: "Other Applications", level: 1 },
      { path: "Other Applications > Volumes", title: "Volumes", level: 2 },
      { path: "Other Applications > Work", title: "Work", level: 2 },
      { path: "Other Applications > Hydrostatic Pressure", title: "Hydrostatic Pressure", level: 2 },
      { path: "Multiple Integrals", title: "Multiple Integrals (Inversion of order / change of coordinates)", level: 1 },
      { path: "Multiple Integrals > Double Integrals", title: "Double Integrals", level: 2 },
      { path: "Multiple Integrals > Triple Integrals", title: "Triple Integrals", level: 2 },
      { path: "Surface Tracing", title: "Surface Tracing", level: 1 },
      { path: "Surface Tracing > Planes", title: "Planes", level: 2 },
      { path: "Surface Tracing > Spheres", title: "Spheres", level: 2 },
      { path: "Surface Tracing > Cylinders", title: "Cylinders", level: 2 },
      { path: "Surface Tracing > Quadric Surfaces", title: "Quadric Surfaces", level: 2 },
      { path: "Surface Tracing > Intersection of Surfaces", title: "Intersection of Surfaces", level: 2 },
      { path: "Multiple Integrals as Volume", title: "Multiple Integrals as Volume", level: 1 },
      { path: "Multiple Integrals as Volume > Double Integrals", title: "Double Integrals", level: 2 },
      { path: "Multiple Integrals as Volume > Triple Integrals", title: "Triple Integrals", level: 2 },
    ],
  },
  {
    subject_code: "DIFFQ",
    subject_title: "Differential Equations",
    topics: [
      { path: "Introduction and Definition", title: "Introduction and Definition", level: 1 },
      { path: "Introduction and Definition > Definition and Classifications of DE", title: "Definition and Classifications of Differential Equations (DE)", level: 2 },
      { path: "Introduction and Definition > Solution of a DE", title: "Solution of a DE", level: 2 },
      { path: "Solution of 1st Order DE", title: "Solution of 1st Order Differential Equations", level: 1 },
      { path: "Solution of 1st Order DE > Variable Separable", title: "Variable Separable", level: 2 },
      { path: "Solution of 1st Order DE > Exact Equation", title: "Exact Equation", level: 2 },
      { path: "Solution of 1st Order DE > Linear Equation", title: "Linear Equation", level: 2 },
      { path: "Solution of 1st Order DE > Substitution Methods", title: "Substitution Methods", level: 2 },
      { path: "Solution of 1st Order DE > Substitution Methods > Homogeneous Coefficients", title: "Homogeneous Coefficients", level: 3 },
      { path: "Solution of 1st Order DE > Substitution Methods > Bernoulli's Equation", title: "Bernoulli's Equation", level: 3 },
      { path: "Solution of 1st Order DE > Substitution Methods > Other Substitution Methods", title: "Other Substitution Methods", level: 3 },
      { path: "Solution of 1st Order DE > Mixed Problems", title: "Mixed Problems (method not pre-identified)", level: 2 },
      { path: "Solution of 1st Order DE > Computer Solutions", title: "Introduction to Use of Computer in Solving Differential Equations", level: 2 },
      { path: "Application of 1st Order DE", title: "Application of 1st Order Differential Equations", level: 1 },
      { path: "Application of 1st Order DE > Decomposition and Growth", title: "Decomposition/Growth", level: 2 },
      { path: "Application of 1st Order DE > Newton's Law of Cooling", title: "Newton's Law of Cooling", level: 2 },
      { path: "Application of 1st Order DE > Mixing", title: "Mixing (non-reacting fluids)", level: 2 },
      { path: "Application of 1st Order DE > Electric Circuits", title: "Electric Circuits", level: 2 },
      { path: "Linear DE of Order n", title: "Linear Differential Equation of Order n", level: 1 },
      { path: "Linear DE of Order n > Introduction", title: "Introduction", level: 2 },
      { path: "Linear DE of Order n > Introduction > Standard Form of nth Order Linear DE", title: "Standard form of a nth order Linear DE", level: 3 },
      { path: "Linear DE of Order n > Introduction > Differential Operators", title: "Differential Operators", level: 3 },
      { path: "Linear DE of Order n > Introduction > Principle of Superposition", title: "Principle of Superposition", level: 3 },
      { path: "Linear DE of Order n > Introduction > Linear Independence of Functions", title: "Linear Independence of a Set of Functions", level: 3 },
      { path: "Linear DE of Order n > Homogeneous Linear DE with Constant Coefficients", title: "Homogeneous Linear Differential Equation with Constant Coefficients", level: 2 },
      { path: "Linear DE of Order n > Non-homogeneous DE with Constant Coefficients", title: "Non-homogeneous Differential Equation with Constant Coefficients", level: 2 },
      { path: "Linear DE of Order n > Non-homogeneous DE with Constant Coefficients > Method of Undetermined Coefficients", title: "Solution by Method of Undetermined Coefficients", level: 3 },
      { path: "Linear DE of Order n > Non-homogeneous DE with Constant Coefficients > Variation of Parameters", title: "Solution by Variation of Parameters", level: 3 },
      { path: "Linear DE of Order n > Computer Solutions", title: "Solution of Higher Order Differential Equations using Computer", level: 2 },
      { path: "Laplace Transforms", title: "Laplace Transforms of Functions", level: 1 },
      { path: "Laplace Transforms > Definition", title: "Definition", level: 2 },
      { path: "Laplace Transforms > Transform of Elementary Functions", title: "Transform of Elementary Functions", level: 2 },
      { path: "Laplace Transforms > First Shifting Theorem", title: "Transform of e^a f(t) - Theorem", level: 2 },
      { path: "Laplace Transforms > Derivatives of Transforms", title: "Transform of t^n f(t) - Derivatives of Transforms", level: 2 },
      { path: "Laplace Transforms > Inverse Transforms", title: "Inverse Transforms", level: 2 },
      { path: "Laplace Transforms > Computer Solutions", title: "Laplace and Inverse Laplace Transforms using a Computer", level: 2 },
      { path: "Laplace Transforms > Transforms of Derivatives", title: "Transforms of Derivatives", level: 2 },
      { path: "Laplace Transforms > Initial Value Problems", title: "Initial Value Problems", level: 2 },
    ],
  },
  {
    subject_code: "ENGDATA",
    subject_title: "Engineering Data Analysis",
    topics: [
      { path: "Obtaining Data", title: "Obtaining Data", level: 1 },
      { path: "Obtaining Data > Methods of Data Collection", title: "Methods of Data Collection", level: 2 },
      { path: "Obtaining Data > Planning and Conducting Surveys", title: "Planning and Conducting Surveys", level: 2 },
      { path: "Obtaining Data > Planning and Conducting Experiments", title: "Planning and Conducting Experiments: Introduction to Design of Experiments", level: 2 },
      { path: "Probability", title: "Probability", level: 1 },
      { path: "Probability > Sample Space and Relationships among Events", title: "Sample Space and Relationships among Events", level: 2 },
      { path: "Probability > Counting Rules", title: "Counting Rules Useful in Probability", level: 2 },
      { path: "Probability > Rules of Probability", title: "Rules of Probability", level: 2 },
      { path: "Discrete Probability Distributions", title: "Discrete Probability Distributions", level: 1 },
      { path: "Discrete Probability Distributions > Random Variables", title: "Random Variables and their Probability Distributions", level: 2 },
      { path: "Discrete Probability Distributions > Cumulative Distribution Functions", title: "Cumulative Distribution Functions", level: 2 },
      { path: "Discrete Probability Distributions > Expected Values", title: "Expected Values of Random Variables", level: 2 },
      { path: "Discrete Probability Distributions > Binomial Distribution", title: "The Binomial Distribution", level: 2 },
      { path: "Discrete Probability Distributions > Poisson Distribution", title: "The Poisson Distribution", level: 2 },
      { path: "Continuous Probability Distribution", title: "Continuous Probability Distribution", level: 1 },
      { path: "Continuous Probability Distribution > Continuous Random Variables", title: "Continuous Random Variables and their Probability Distribution", level: 2 },
      { path: "Continuous Probability Distribution > Expected Values of Continuous Random Variables", title: "Expected Values of Continuous Random Variables", level: 2 },
      { path: "Continuous Probability Distribution > Normal Distribution", title: "Normal Distribution", level: 2 },
      { path: "Continuous Probability Distribution > Normal Approximation to Binomial and Poisson", title: "Normal Approximation to the Binomial and Poisson Distribution", level: 2 },
      { path: "Continuous Probability Distribution > Exponential Distribution", title: "Exponential Distribution", level: 2 },
      { path: "Joint Probability Distribution", title: "Joint Probability Distribution", level: 1 },
      { path: "Joint Probability Distribution > Two or More Random Variables", title: "Two or More Random Variables", level: 2 },
      { path: "Joint Probability Distribution > Linear Functions of Random Variables", title: "Linear Functions of Random Variables", level: 2 },
      { path: "Joint Probability Distribution > General Functions of Random Variables", title: "General Functions of Random Variables", level: 2 },
      { path: "Sampling Distributions and Point Estimation", title: "Sampling Distributions and Point Estimation of Parameters", level: 1 },
      { path: "Sampling Distributions and Point Estimation > Point Estimation", title: "Point Estimation", level: 2 },
      { path: "Sampling Distributions and Point Estimation > Central Limit Theorem", title: "Sampling Distribution and the Central Limit Theorem", level: 2 },
      { path: "Sampling Distributions and Point Estimation > Unbiased Estimator", title: "Unbiased Estimator", level: 2 },
      { path: "Sampling Distributions and Point Estimation > Standard Error", title: "Standard Error", level: 2 },
      { path: "Sampling Distributions and Point Estimation > Mean Squared Error", title: "Mean Squared Error of an Estimator", level: 2 },
      { path: "Statistical Intervals", title: "Statistical Intervals", level: 1 },
      { path: "Statistical Intervals > Confidence Intervals Single Sample", title: "Confidence Intervals: Single Sample", level: 2 },
      { path: "Statistical Intervals > Confidence Intervals Multiple Samples", title: "Confidence Intervals: Multiple Samples", level: 2 },
      { path: "Statistical Intervals > Prediction Intervals", title: "Prediction Intervals", level: 2 },
      { path: "Statistical Intervals > Tolerance Intervals", title: "Tolerance Intervals", level: 2 },
      { path: "Test of Hypothesis for Single Sample", title: "Test of Hypothesis for a Single Sample", level: 1 },
      { path: "Test of Hypothesis for Single Sample > Hypothesis Testing Concepts", title: "Hypothesis Testing", level: 2 },
      { path: "Test of Hypothesis for Single Sample > Test on Mean Variance Known", title: "Test on the Mean of a Normal Distribution, Variance Known", level: 2 },
      { path: "Test of Hypothesis for Single Sample > Test on Mean Variance Unknown", title: "Test on the Mean of a Normal Distribution, Variance Unknown", level: 2 },
      { path: "Test of Hypothesis for Single Sample > Test on Variance", title: "Test on the Variance and Statistical Deviation of a Normal Distribution", level: 2 },
      { path: "Test of Hypothesis for Single Sample > Test on Population Proportion", title: "Test on a Population Proportion", level: 2 },
      { path: "Statistical Inference of Two Samples", title: "Statistical Inference of Two Samples", level: 1 },
      { path: "Statistical Inference of Two Samples > Difference in Means Variances Known", title: "Inference on the Difference in Means of Two Normal Distributions, Variances Known", level: 2 },
      { path: "Statistical Inference of Two Samples > Difference in Means Variances Unknown", title: "Inference on the Difference in Means of Two Normal Distributions, Variances Unknown", level: 2 },
      { path: "Statistical Inference of Two Samples > Variance of Two Normal Distributions", title: "Inference on the Variance of Two Normal Distributions", level: 2 },
      { path: "Statistical Inference of Two Samples > Two Population Proportions", title: "Inference on Two Population Proportions", level: 2 },
      { path: "Simple Linear Regression and Correlation", title: "Simple Linear Regression and Correlation", level: 1 },
      { path: "Simple Linear Regression and Correlation > Empirical Models", title: "Empirical Models", level: 2 },
      { path: "Simple Linear Regression and Correlation > Least-Squares Approach", title: "Regression: Modelling Linear Relationships - The Least-Squares Approach", level: 2 },
      { path: "Simple Linear Regression and Correlation > Correlation", title: "Correlation: Estimating the Strength of Linear Relation", level: 2 },
      { path: "Simple Linear Regression and Correlation > Hypothesis Tests", title: "Hypothesis Tests in Simple Linear Regression", level: 2 },
      { path: "Simple Linear Regression and Correlation > Prediction of New Observations", title: "Prediction of New Observations", level: 2 },
      { path: "Simple Linear Regression and Correlation > Adequacy of the Regression Model", title: "Adequacy of the Regression Model", level: 2 },
    ],
  },
  // ============================================================
  // B. NATURAL/PHYSICAL SCIENCES
  // ============================================================
  {
    subject_code: "CHEMENG",
    subject_title: "Chemistry for Engineers",
    topics: [
      { path: "Energy", title: "Energy", level: 1 },
      { path: "Energy > Electrochemical Energy", title: "Electrochemical Energy", level: 2 },
      { path: "Energy > Nuclear Chemistry and Energy", title: "Nuclear Chemistry and Energy", level: 2 },
      { path: "Energy > Fuels", title: "Fuels", level: 2 },
      { path: "The Chemistry of Engineering Materials", title: "The Chemistry of Engineering Materials", level: 1 },
      { path: "The Chemistry of Engineering Materials > Basic Concepts of Crystal Structure", title: "Basic Concepts of Crystal Structure", level: 2 },
      { path: "The Chemistry of Engineering Materials > Metals", title: "Metals", level: 2 },
      { path: "The Chemistry of Engineering Materials > Polymers", title: "Polymers", level: 2 },
      { path: "The Chemistry of Engineering Materials > Engineered Nanomaterials", title: "Engineered Nanomaterials", level: 2 },
      { path: "The Chemistry of the Environment", title: "The Chemistry of the Environment", level: 1 },
      { path: "The Chemistry of the Environment > Chemistry of the Atmosphere", title: "The Chemistry of the Atmosphere", level: 2 },
      { path: "The Chemistry of the Environment > Chemistry of Water", title: "The Chemistry of Water", level: 2 },
      { path: "The Chemistry of the Environment > Soil Chemistry", title: "Soil Chemistry", level: 2 },
      { path: "Chemical Safety", title: "Chemical Safety", level: 1 },
      { path: "Special Topics", title: "Special Topics Specific to Field of Expertise", level: 1 },
    ],
  },
  {
    subject_code: "CHEMLAB",
    subject_title: "Chemistry for Engineers (Laboratory)",
    topics: [
      { path: "Calorimetry", title: "Calorimetry", level: 1 },
      { path: "Heat of Combustion", title: "Heat of Combustion", level: 1 },
      { path: "Metals and Aspects of Corrosion", title: "Metals and Some Aspects of Corrosion", level: 1 },
      { path: "Mechanical Properties of Materials", title: "Mechanical Properties of Materials", level: 1 },
      { path: "Water Properties and Purification", title: "Water: Its Properties and Purification", level: 1 },
      { path: "Dissolved Oxygen Content of Water", title: "Determination of the Dissolved Oxygen Content of Water", level: 1 },
      { path: "Cigarette Smoking and Air Pollution", title: "Cigarette Smoking and Air Pollution", level: 1 },
      { path: "Nuclear Reactions", title: "Nuclear Reactions, Binding Energy and Rate of Decay", level: 1 },
      { path: "Crystal Lattices and Unit Cells", title: "Crystal Lattices and Unit Cells", level: 1 },
      { path: "Community Immersion", title: "Community Immersion: Care for the Environment", level: 1 },
    ],
  },
  {
    subject_code: "PHYSENG",
    subject_title: "Physics for Engineers",
    topics: [
      { path: "Work, Energy and Power", title: "Work, Energy and Power", level: 1 },
      { path: "Impulse and Momentum", title: "Impulse and Momentum", level: 1 },
      { path: "Kinematics", title: "Kinematics", level: 1 },
      { path: "Dynamics", title: "Dynamics", level: 1 },
      { path: "Rotation", title: "Rotation", level: 1 },
      { path: "Dynamics of Rotation", title: "Dynamics of Rotation", level: 1 },
      { path: "Elasticity", title: "Elasticity", level: 1 },
      { path: "Oscillations", title: "Oscillations", level: 1 },
      { path: "Fluids", title: "Fluids", level: 1 },
      { path: "Heat Transfer", title: "Heat Transfer", level: 1 },
      { path: "Waves", title: "Waves", level: 1 },
      { path: "Electrostatics", title: "Electrostatics", level: 1 },
      { path: "Electricity", title: "Electricity", level: 1 },
      { path: "Magnetism", title: "Magnetism", level: 1 },
      { path: "Optics", title: "Optics", level: 1 },
    ],
  },
  // ============================================================
  // C. BASIC ENGINEERING SCIENCES
  // ============================================================
  {
    subject_code: "ENGDWG",
    subject_title: "Engineering Drawing",
    topics: [
      { path: "Engineering Lettering", title: "Engineering Lettering", level: 1 },
      { path: "Instrumental Figures", title: "Instrumental Figures", level: 1 },
      { path: "Geometric Construction", title: "Geometric Construction", level: 1 },
      { path: "Orthographic Projection", title: "Orthographic Projection", level: 1 },
      { path: "Dimensioning", title: "Dimensioning", level: 1 },
      { path: "Orthographic Views with Dimensions and Section View", title: "Orthographic Views with Dimensions and Section View", level: 1 },
      { path: "Sectional View", title: "Sectional View", level: 1 },
      { path: "Pictorial Drawing", title: "Pictorial Drawing", level: 1 },
      { path: "Engineering Working Drawings", title: "Engineering Working Drawings", level: 1 },
      { path: "Assembly and Exploded Detailed Drawings", title: "Assembly and Exploded Detailed Drawings", level: 1 },
    ],
  },
  {
    subject_code: "CAD",
    subject_title: "Computer-Aided Drafting",
    topics: [
      { path: "Introduction to CAD Software", title: "Introduction to CAD Software", level: 1 },
      { path: "CAD Drawing", title: "CAD Drawing", level: 1 },
      { path: "Snapping and Construction Elements", title: "Snapping, Construction Elements", level: 1 },
      { path: "Dimensioning", title: "Dimensioning", level: 1 },
      { path: "Plotting and Inputting Images", title: "Plotting, Inputting Images", level: 1 },
      { path: "3D and Navigating in 3D", title: "3D and Navigating in 3D", level: 1 },
      { path: "Rendering", title: "Rendering", level: 1 },
    ],
  },
  {
    subject_code: "STATICS",
    subject_title: "Statics of Rigid Bodies",
    topics: [
      { path: "Introduction to Mechanics and Vector Operations", title: "Introduction to Mechanics; Vector Operations", level: 1 },
      { path: "Force Vectors and Equilibrium of Particles", title: "Force Vectors and Equilibrium of Particles", level: 1 },
      { path: "Vector Cross and Dot Product", title: "Vector Cross and Dot Product", level: 1 },
      { path: "Moment of a Force", title: "Moment of a Force", level: 1 },
      { path: "Couples and Moment of a Couple", title: "Couples; Moment of a Couple", level: 1 },
      { path: "Equivalent Force Systems in 2D and 3D", title: "Equivalent Force Systems in 2D and 3D", level: 1 },
      { path: "Dry Static Friction, Wedge and Belt Friction", title: "Dry Static Friction, Wedge and Belt Friction", level: 1 },
      { path: "Centroid, Center of Mass, Center of Gravity", title: "Centroid; Center of Mass; and Center of Gravity", level: 1 },
      { path: "Distributed Loads, Hydrostatic Forces, Cables", title: "Distributed Loads and Hydrostatic Forces; Cables", level: 1 },
      { path: "Moment of Inertia, Mass Moment of Inertia", title: "Moment of Inertia; Mass Moment of Inertia", level: 1 },
      { path: "Beams, Shear and Bending Moment Diagrams", title: "Beams; Shear and Bending Moment Diagrams", level: 1 },
    ],
  },
  {
    subject_code: "DYNAMICS",
    subject_title: "Dynamics of Rigid Bodies",
    topics: [
      { path: "Introduction to Dynamics", title: "Introduction to Dynamics", level: 1 },
      { path: "Position, Velocity, and Acceleration", title: "Position, Velocity, and Acceleration", level: 1 },
      { path: "Determination of Motion of Particles", title: "Determination of the Motion of the Particles", level: 1 },
      { path: "Uniform Rectilinear Motion", title: "Uniform Rectilinear Motion", level: 1 },
      { path: "Uniformly Accelerated Rectilinear Motion", title: "Uniformly Accelerated Rectilinear Motion", level: 1 },
      { path: "Position Vector, Velocity, and Acceleration", title: "Position Vector, Velocity, and Acceleration", level: 1 },
      { path: "Derivatives of Vector Functions", title: "Derivatives of Vector Functions", level: 1 },
      { path: "Rectangular Components of Velocity and Acceleration", title: "Rectangular Components of Velocity and Acceleration", level: 1 },
      { path: "Motion Relative to a Frame in Translation", title: "Motion Relative to a Frame in Translation", level: 1 },
      { path: "Tangential and Normal Components", title: "Tangential and Normal Components", level: 1 },
      { path: "Radial and Transverse Components", title: "Radial and Transverse Components", level: 1 },
      { path: "Motion of Several Particles (Dependent Motion)", title: "Motion of Several Particles (Dependent Motion)", level: 1 },
      { path: "Kinetics of Particles: Newton's Second Law", title: "Kinetics of Particles: Newton's Second Law", level: 1 },
      { path: "Kinetics of Particles: Newton's Second Law > Newton's Second Law of Motion", title: "Newton's Second Law of Motion", level: 2 },
      { path: "Kinetics of Particles: Newton's Second Law > Linear Momentum", title: "Linear Momentum of the Particle, Rate of Change of Linear Momentum", level: 2 },
      { path: "Kinetics of Particles: Newton's Second Law > Dynamic Equilibrium", title: "Dynamic Equilibrium", level: 2 },
      { path: "Kinetics of Particles: Newton's Second Law > Angular Momentum", title: "Angular Momentum of Particle, Rate of Change of Angular Momentum", level: 2 },
      { path: "Kinetics of Particles: Energy and Momentum Methods", title: "Kinetics of Particles: Energy and Momentum Methods", level: 1 },
      { path: "Kinetics of Particles: Energy and Momentum Methods > Work of Force", title: "Work of Force", level: 2 },
      { path: "Kinetics of Particles: Energy and Momentum Methods > Kinetic Energy and Work-Energy Principle", title: "Kinetic Energy of a Particle, Principle of Work and Energy", level: 2 },
      { path: "Systems of Particles", title: "Systems of Particles", level: 1 },
      { path: "Kinematics of Rigid Bodies", title: "Kinematics of Rigid Bodies", level: 1 },
      { path: "Kinematics of Rigid Bodies > Translation", title: "Translation", level: 2 },
      { path: "Kinematics of Rigid Bodies > Rotation About a Fixed Axis", title: "Rotation About a Fixed Axis", level: 2 },
      { path: "Kinematics of Rigid Bodies > General Plane Motion", title: "General Plane Motion", level: 2 },
      { path: "Kinematics of Rigid Bodies > Absolute and Relative Velocity in Plane Motion", title: "Absolute and Relative Velocity in Plane Motion", level: 2 },
      { path: "Kinematics of Rigid Bodies > Instantaneous Center of Rotation", title: "Instantaneous Center of Rotation in Plane Motion", level: 2 },
      { path: "Kinematics of Rigid Bodies > Coriolis Acceleration", title: "Plane Motion of a Particle Relative to a Rotating Frame; Coriolis Acceleration", level: 2 },
      { path: "Plane Motion of Rigid Bodies: Forces and Accelerations", title: "Plane Motion of Rigid Bodies: Forces and Accelerations", level: 1 },
      { path: "Plane Motion of Rigid Bodies: Forces and Accelerations > Angular Momentum in Plane Motion", title: "Angular Momentum of a Rigid Body in Plane Motion", level: 2 },
      { path: "Plane Motion of Rigid Bodies: Forces and Accelerations > D'Alembert's Principle", title: "Plane Motion of a Rigid Body. D'Alembert's Principle", level: 2 },
      { path: "Plane Motion of Rigid Bodies: Energy and Momentum Methods", title: "Plane Motion of Rigid Bodies: Energy and Momentum Methods", level: 1 },
      { path: "Plane Motion of Rigid Bodies: Energy and Momentum Methods > Work and Energy for Rigid Body", title: "Principle of Work and Energy for a Rigid Body", level: 2 },
      { path: "Plane Motion of Rigid Bodies: Energy and Momentum Methods > Kinetic Energy in Plane Motion", title: "Kinetic Energy of a Rigid Body in Plane Motion", level: 2 },
      { path: "Plane Motion of Rigid Bodies: Energy and Momentum Methods > Impulse and Momentum", title: "Principle of Impulse and Momentum", level: 2 },
    ],
  },
  {
    subject_code: "MECHDEF",
    subject_title: "Mechanics of Deformable Bodies",
    topics: [
      { path: "Load Classification", title: "Load Classification", level: 1 },
      { path: "Concept of Stress", title: "Concept of Stress, Normal and Shear Stress", level: 1 },
      { path: "Stresses under Centric Loading", title: "Stresses under Centric Loading", level: 1 },
      { path: "Stress Concentration", title: "Stress Concentration", level: 1 },
      { path: "Plane Stress", title: "Plane Stress", level: 1 },
      { path: "Principal Stresses for Plane Stress", title: "Principal Stresses for Plane Stress", level: 1 },
      { path: "Mohr's Circle for Plane Stress", title: "Mohr's Circle for Plane Stress", level: 1 },
      { path: "Deformations, Normal and Shear Strains", title: "Deformations, Normal and Shear Strains", level: 1 },
      { path: "Material Properties", title: "Material Properties", level: 1 },
      { path: "Working Stresses", title: "Working Stresses", level: 1 },
      { path: "Deformation in Axially Loaded Members", title: "Deformation in a System of Axially Loaded Members", level: 1 },
      { path: "Temperature Effects on Axially Loaded Members", title: "Temperature Effects on Axially Loaded Members", level: 1 },
      { path: "Statically Indeterminate Members", title: "Statically Indeterminate Members", level: 1 },
      { path: "Thin-Walled Pressure Vessel", title: "Thin-Walled Pressure Vessel", level: 1 },
      { path: "Torsional Stresses", title: "Torsional Stresses; Elastic Torsion Formula", level: 1 },
      { path: "Torsional Deformation and Power Transmission", title: "Torsional Deformation; Power Transmission", level: 1 },
      { path: "Flexural Stresses by the Elastic Curve", title: "Flexural Stresses by the Elastic Curve", level: 1 },
      { path: "Moment Equation Using Singularity Function", title: "Moment Equation Using Singularity Function", level: 1 },
      { path: "Beam Deflection by Double Integration Method", title: "Beam Deflection by the Double Integration Method", level: 1 },
      { path: "Area Moment Theorems", title: "Area Moment Theorems", level: 1 },
      { path: "Moment Diagram by Parts", title: "Moment Diagram by Parts", level: 1 },
      { path: "Beam Deflection by Area Moment Method", title: "Beam Deflection by Area Moment Method", level: 1 },
      { path: "Statically Indeterminate Beams", title: "Statically Indeterminate Beams", level: 1 },
      { path: "Buckling of Long Straight Columns", title: "Buckling of Long Straight Columns", level: 1 },
      { path: "Combined Loadings", title: "Combined Loadings", level: 1 },
      { path: "Analysis of Riveted Connections", title: "Analysis of Riveted Connections by the Uniform Shear Method", level: 1 },
      { path: "Welded Connections", title: "Welded Connections", level: 1 },
    ],
  },
  {
    subject_code: "ENGECON",
    subject_title: "Engineering Economics",
    topics: [
      { path: "Introduction", title: "Introduction", level: 1 },
      { path: "Introduction > Definitions", title: "Definitions", level: 2 },
      { path: "Introduction > Principles of Engineering Economics", title: "Principles of Engineering Economics", level: 2 },
      { path: "Introduction > Engineering Economics and the Design Process", title: "Engineering Economics and the Design Process", level: 2 },
      { path: "Introduction > Cost Concepts for Decision Making", title: "Cost Concepts for Decision Making", level: 2 },
      { path: "Introduction > Present Economic Studies", title: "Present Economic Studies", level: 2 },
      { path: "Money-Time Relationships and Equivalence", title: "Money-Time Relationships and Equivalence", level: 1 },
      { path: "Money-Time Relationships and Equivalence > Interest and Time Value of Money", title: "Interest and the Time Value of Money", level: 2 },
      { path: "Money-Time Relationships and Equivalence > The Concept of Equivalence", title: "The Concept of Equivalence", level: 2 },
      { path: "Money-Time Relationships and Equivalence > Cash Flows", title: "Cash Flows", level: 2 },
      { path: "Economic Study Methods", title: "Economic Study Methods", level: 1 },
      { path: "Economic Study Methods > Minimum Attractive Rate of Return", title: "The Minimum Attractive Rate of Return", level: 2 },
      { path: "Economic Study Methods > Basic Economic Study Methods", title: "Basic Economic Study Methods: Present Worth, Future Worth, Annual Worth, IRR, ERR", level: 2 },
      { path: "Economic Study Methods > Other Methods", title: "Other Methods: Discounted Payback Period, Benefit/Cost Ratio", level: 2 },
      { path: "Decisions Under Certainty", title: "Decisions Under Certainty", level: 1 },
      { path: "Decisions Under Certainty > Evaluation of Mutually Exclusive Alternatives", title: "Evaluation of Mutually Exclusive Alternatives", level: 2 },
      { path: "Decisions Under Certainty > Evaluation of Independent Projects", title: "Evaluation of Independent Projects", level: 2 },
      { path: "Decisions Under Certainty > Effects of Inflation", title: "Effects of Inflation", level: 2 },
      { path: "Decisions Under Certainty > Depreciation and After-Tax Economic Analysis", title: "Depreciation and After-Tax Economic Analysis", level: 2 },
      { path: "Decisions Under Certainty > Replacement Studies", title: "Replacement Studies", level: 2 },
      { path: "Decisions Recognizing Risk", title: "Decisions Recognizing Risk", level: 1 },
      { path: "Decisions Recognizing Risk > Expected Monetary Value", title: "Expected Monetary Value of Alternatives", level: 2 },
      { path: "Decisions Recognizing Risk > Discounted Decision Tree Analysis", title: "Discounted Decision Tree Analysis", level: 2 },
      { path: "Decisions Admitting Uncertainty", title: "Decisions Admitting Uncertainty", level: 1 },
      { path: "Decisions Admitting Uncertainty > Sensitivity Analysis", title: "Sensitivity Analysis", level: 2 },
      { path: "Decisions Admitting Uncertainty > Decision Analysis Models", title: "Decision Analysis Models", level: 2 },
    ],
  },
  {
    subject_code: "ENGMGT",
    subject_title: "Engineering Management",
    topics: [
      { path: "Introduction to Engineering Management", title: "Introduction to Engineering Management", level: 1 },
      { path: "Decision Making", title: "Decision Making", level: 1 },
      { path: "Functions of Management", title: "Functions of Management", level: 1 },
      { path: "Functions of Management > Planning and Coordinating", title: "Planning / Coordinating", level: 2 },
      { path: "Functions of Management > Organizing", title: "Organizing", level: 2 },
      { path: "Functions of Management > Staffing", title: "Staffing", level: 2 },
      { path: "Functions of Management > Communicating", title: "Communicating", level: 2 },
      { path: "Functions of Management > Motivating", title: "Motivating", level: 2 },
      { path: "Functions of Management > Leading", title: "Leading", level: 2 },
      { path: "Functions of Management > Controlling", title: "Controlling", level: 2 },
      { path: "Managing Product and Service Operations", title: "Managing Product and Service Operations", level: 1 },
      { path: "Managing the Marketing Function", title: "Managing the Marketing Function", level: 1 },
      { path: "Managing the Finance Function", title: "Managing the Finance Function", level: 1 },
    ],
  },
  {
    subject_code: "TECHPRE",
    subject_title: "Technopreneurship 101",
    topics: [
      { path: "Introduction", title: "Introduction", level: 1 },
      { path: "Introduction > Entrepreneurial Mindset", title: "Entrepreneurial Mindset", level: 2 },
      { path: "Introduction > Innovation and Ideas", title: "Innovation and Ideas", level: 2 },
      { path: "Introduction > Products and Services", title: "Products and Services", level: 2 },
      { path: "Introduction > Team Formation", title: "Team Formation", level: 2 },
      { path: "Customers", title: "Customers", level: 1 },
      { path: "Value Proposition", title: "Value Proposition", level: 1 },
      { path: "Market Identification and Analysis", title: "Market Identification and Analysis", level: 1 },
      { path: "Creating Competitive Advantage", title: "Creating Competitive Advantage", level: 1 },
      { path: "Business Models", title: "Business Models", level: 1 },
      { path: "Introduction to Intellectual Property", title: "Introduction to Intellectual Property", level: 1 },
      { path: "Execution and Business Plan", title: "Execution and Business Plan", level: 1 },
      { path: "Financial Analysis and Accounting Basics", title: "Financial Analysis and Accounting Basics", level: 1 },
      { path: "Raising Capital", title: "Raising Capital", level: 1 },
      { path: "Ethics, Social Responsibility, and Globalization", title: "Ethics, Social Responsibility, and Globalization", level: 1 },
    ],
  },
  // ============================================================
  // D. ALLIED COURSES
  // ============================================================
  {
    subject_code: "BASEE",
    subject_title: "Basic Electrical Engineering",
    topics: [
      { path: "Circuit Elements and Variables", title: "Definitions, Symbols, Types of Circuit Elements, Circuit Variables and Parameters", level: 1 },
      { path: "Resistance", title: "Resistance", level: 1 },
      { path: "Resistance > Definition and Factors Affecting Resistance", title: "Definition, Factor that Affect Resistance of a Conductor, Resistivity", level: 2 },
      { path: "Resistance > Temperature Dependence", title: "Resistance as a Function of Temperature, Conductance", level: 2 },
      { path: "Ohm's Law, Electrical Power, Electrical Energy", title: "Ohm's Law, Electrical Power, Electrical Energy", level: 1 },
      { path: "Heating Effect of Electric Current", title: "Heating Effect of Electric Current", level: 1 },
      { path: "Connection of Resistors", title: "Connection of Resistors", level: 1 },
      { path: "Connection of Resistors > Resistors in Series", title: "Characteristics of Resistors in Series", level: 2 },
      { path: "Connection of Resistors > Resistors in Parallel", title: "Characteristics of Resistors in Parallel", level: 2 },
      { path: "Connection of Resistors > Resistors in Series-Parallel", title: "Characteristics of Resistors in Series-Parallel", level: 2 },
      { path: "Connection of Resistors > Application to Meters", title: "Application of Series and Parallel Connection of Resistors to Meters", level: 2 },
      { path: "Network Reduction", title: "Network Reduction (Delta-Wye Transformation)", level: 1 },
      { path: "Maximum Power Transfer in DC Circuits", title: "Maximum Power Transfer in DC Circuits", level: 1 },
      { path: "Cells and Batteries", title: "Cells and Batteries", level: 1 },
      { path: "Cells and Batteries > Electrochemical Cells", title: "Electrochemical Cells", level: 2 },
      { path: "Cells and Batteries > Battery Cells in Series", title: "Battery Cells in Series", level: 2 },
      { path: "Cells and Batteries > Battery Cells in Parallel", title: "Battery Cells in Parallel", level: 2 },
      { path: "Cells and Batteries > Series-Parallel Grouping", title: "Series-Parallel Grouping of Cells", level: 2 },
      { path: "Laws, Theorems and Methods in Network Analysis", title: "Laws, Theorems and Methods Used in Network Analysis", level: 1 },
      { path: "Laws, Theorems and Methods in Network Analysis > Kirchhoff's Laws", title: "Kirchhoff's Laws", level: 2 },
      { path: "Laws, Theorems and Methods in Network Analysis > Maxwell's Method", title: "Maxwell's Method", level: 2 },
      { path: "Laws, Theorems and Methods in Network Analysis > Superposition Theorem", title: "Superposition Theorem", level: 2 },
      { path: "Laws, Theorems and Methods in Network Analysis > Thevenin's Theorem", title: "Thevenin's Theorem", level: 2 },
      { path: "Laws, Theorems and Methods in Network Analysis > Norton's Theorem", title: "Norton's Theorem", level: 2 },
      { path: "Inductors", title: "Inductors", level: 1 },
      { path: "Capacitors", title: "Capacitors", level: 1 },
      { path: "Alternating Current Circuits", title: "Alternating Current Circuits", level: 1 },
      { path: "Alternating Current Circuits > Definition of AC", title: "Definition of AC", level: 2 },
      { path: "Alternating Current Circuits > Nomenclature of Periodic Waves", title: "Nomenclature of Periodic Waves", level: 2 },
      { path: "Alternating Current Circuits > Equations of Sinusoidal Current and Voltage", title: "Equations of Continuous Sinusoidal Current and Voltage", level: 2 },
      { path: "Alternating Current Circuits > Phase Angle", title: "Phase Angle, Phase Angle Difference, Leading Wave, Lagging Wave", level: 2 },
      { path: "Alternating Current Circuits > Impedance Function", title: "Impedance Function", level: 2 },
      { path: "Voltage and Current Relations", title: "Voltage and Current Relations in Various Circuits", level: 1 },
      { path: "Voltage and Current Relations > Pure Resistive Circuit", title: "Pure Resistive Circuit", level: 2 },
      { path: "Voltage and Current Relations > Pure Inductive Circuit", title: "Pure Inductive Circuit", level: 2 },
      { path: "Voltage and Current Relations > Pure Capacitive Circuit", title: "Pure Capacitive Circuit", level: 2 },
      { path: "Voltage and Current Relations > Series RL Circuit", title: "Series RL Circuit", level: 2 },
      { path: "Voltage and Current Relations > Series RC Circuit", title: "Series RC Circuit", level: 2 },
      { path: "Voltage and Current Relations > Series RLC Circuit", title: "Series RLC Circuit", level: 2 },
      { path: "Effective Value of AC", title: "Effective Value of AC", level: 1 },
      { path: "Phasor Algebra", title: "Phasor Algebra", level: 1 },
      { path: "Phasor Algebra > Impedance Complex Circuit", title: "Impedance Complex Circuit", level: 2 },
      { path: "Conductance, Susceptance and Admittance", title: "Conductance, Susceptance and Admittance of AC Circuit", level: 1 },
      { path: "Power Factor Correction", title: "Power Factor Correction", level: 1 },
    ],
  },
  {
    subject_code: "BASICELEC",
    subject_title: "Basic Electronics",
    topics: [
      { path: "Introduction to Electronics", title: "Introduction to Electronics", level: 1 },
      { path: "Introduction to Electronics > Definition, History and Application", title: "Definition, History and Application of Electronics", level: 2 },
      { path: "Introduction to Electronics > Common Electronics Components", title: "Common Electronics Components", level: 2 },
      { path: "Introduction to Electronics > Solid State Fundamentals", title: "Solid State Fundamentals: Conductor, Insulator, Semiconductor", level: 2 },
      { path: "Semiconductor PN Junction Diode", title: "Semiconductor PN Junction Diode", level: 1 },
      { path: "Semiconductor PN Junction Diode > Construction and Operation", title: "Construction and Operation, Characteristic Curve", level: 2 },
      { path: "Semiconductor PN Junction Diode > Diode Equivalent Model", title: "Diode Equivalent Model", level: 2 },
      { path: "Semiconductor PN Junction Diode > Diode Circuit Analysis", title: "Diode Circuit Analysis", level: 2 },
      { path: "Semiconductor PN Junction Diode > Light Emitting Diode", title: "Light Emitting Diode", level: 2 },
      { path: "DC Regulated Power Supply", title: "DC Regulated Power Supply", level: 1 },
      { path: "DC Regulated Power Supply > Block Diagram, Transformer, Rectifier", title: "Block Diagram, Transformer, Rectifier", level: 2 },
      { path: "DC Regulated Power Supply > Simple Capacitor Filter", title: "Simple Capacitor Filter", level: 2 },
      { path: "DC Regulated Power Supply > Voltage Regulator", title: "Voltage Regulator", level: 2 },
      { path: "Bipolar Junction Transistor", title: "Bipolar Junction Transistor (BJT)", level: 1 },
      { path: "Bipolar Junction Transistor > Construction and Schematic Symbol", title: "Construction and Schematic Symbol", level: 2 },
      { path: "Bipolar Junction Transistor > Region of Operation and Characteristic Curve", title: "Region of Operation and Characteristic Curve of BJT, Eber's Moll Model", level: 2 },
      { path: "Bipolar Junction Transistor > Amplification Factors", title: "Amplification Factors and Basic BJT Formula, Switching Transistor Circuit", level: 2 },
      { path: "Bipolar Junction Transistor > BJT Amplifier Configuration", title: "BJT Amplifier Configuration", level: 2 },
      { path: "Bipolar Junction Transistor > BJT Amplifier Circuit Analysis", title: "BJT Amplifier Circuit Analysis", level: 2 },
      { path: "Bipolar Junction Transistor > FET Amplifier", title: "FET Amplifier Regulation", level: 2 },
      { path: "Bipolar Junction Transistor > JFET and MOSFET DC Analysis", title: "JFET and MOSFET DC Analysis", level: 2 },
      { path: "Bipolar Junction Transistor > FET AC Small Signal Analysis", title: "FET AC Small Signal Analysis", level: 2 },
      { path: "Operational Amplifiers", title: "Operational Amplifiers", level: 1 },
      { path: "Operational Amplifiers > Block Diagram", title: "Block Diagram", level: 2 },
      { path: "Operational Amplifiers > Characteristics and Equivalent Circuit", title: "Characteristics and Equivalent Circuit", level: 2 },
      { path: "Operational Amplifiers > Op-amp Closed Loop Operation", title: "Op-amp Closed Loop Operation", level: 2 },
    ],
  },
  {
    subject_code: "DCAC",
    subject_title: "DC and AC Machinery",
    topics: [
      { path: "DC Generators", title: "DC Generators", level: 1 },
      { path: "Shunt and Compound Motors", title: "Shunt and Compound Motors", level: 1 },
      { path: "Single Phase Transformer", title: "Single Phase Transformer", level: 1 },
      { path: "Three-Phase Alternator", title: "Three-Phase Alternator", level: 1 },
      { path: "Induction Motors", title: "Induction Motors", level: 1 },
      { path: "Synchronous Motors", title: "Synchronous Motors", level: 1 },
    ],
  },
  // ============================================================
  // E. FUNDAMENTAL MECHANICAL ENGINEERING COURSES
  // ============================================================
  {
    subject_code: "MEORIENT",
    subject_title: "Mechanical Engineering Orientation",
    topics: [
      { path: "Mechanical Engineering Program", title: "Mechanical Engineering Program", level: 1 },
      { path: "Teamwork and Communication Skills", title: "Teamwork and Communication Skills", level: 1 },
      { path: "Engineering Profession", title: "Engineering Profession", level: 1 },
      { path: "Engineering as a Career", title: "Engineering as a Career", level: 1 },
      { path: "Developing Good Study Habits", title: "Developing Good Study Habits", level: 1 },
      { path: "Engineering Design and Creativity", title: "Engineering Design and Creativity", level: 1 },
    ],
  },
  {
    subject_code: "ADVME",
    subject_title: "Advanced Mathematics for ME",
    topics: [
      { path: "Numerical Methods: Introduction", title: "Numerical Methods: Introduction, Discrete Algebra, Accuracy, Errors", level: 1 },
      { path: "Numerical Analysis in Engineering", title: "Numerical Analysis in Engineering. The Taylor Series", level: 1 },
      { path: "Review of Matrices", title: "Review of Matrices. Operations, Vectors, Determinants, Rank", level: 1 },
      { path: "Solutions to Linear Systems of Equations", title: "Solutions to Linear Systems of Equations", level: 1 },
      { path: "Roots of Equations", title: "Roots of Equations", level: 1 },
      { path: "Interpolation and Curve Fitting", title: "Interpolation. Least Square Approximations. Curve Fitting. Optimization", level: 1 },
      { path: "Numerical Differentiation", title: "Numerical Differentiation", level: 1 },
      { path: "Numerical Integration Methods", title: "Numerical Integration Methods (time integration methods, Runge Kutta)", level: 1 },
      { path: "Solution to Non-Linear Equations", title: "Solution to Non-Linear Equations", level: 1 },
      { path: "Numerical Solution to ODE", title: "Numerical Solution to Ordinary Differential Equations (ODE) and Systems of ODE", level: 1 },
      { path: "Numerical Solution to PDE", title: "Numerical Solution to Partial Differential Equations (Advanced Topic)", level: 1 },
      { path: "Computer Programming Exercises", title: "Computer Programming Exercises and Examples", level: 1 },
    ],
  },
  {
    subject_code: "METHRES",
    subject_title: "Methods of Research for ME",
    topics: [
      { path: "Nature and Characteristics of Research", title: "Nature and Characteristics of Research", level: 1 },
      { path: "Types of Research", title: "Types of Research", level: 1 },
      { path: "Types of Research > Basic", title: "Basic Research", level: 2 },
      { path: "Types of Research > Applied", title: "Applied Research", level: 2 },
      { path: "Types of Research > Pure", title: "Pure Research", level: 2 },
      { path: "Research Problems and Objectives", title: "Research Problems and Objectives", level: 1 },
      { path: "Research Problems and Objectives > Purpose of Research", title: "Purpose of Research", level: 2 },
      { path: "Research Problems and Objectives > Developing Research Objectives", title: "Developing Research Objectives", level: 2 },
      { path: "Review of Related Literature", title: "Review of Related Literature", level: 1 },
      { path: "Review of Related Literature > Conceptual Literature", title: "Conceptual Literature", level: 2 },
      { path: "Review of Related Literature > Research Literature", title: "Research Literature", level: 2 },
      { path: "Review of Related Literature > Referencing", title: "Referencing", level: 2 },
      { path: "Research Design", title: "Research Design", level: 1 },
      { path: "Research Design > Experimental Design", title: "Experimental Design", level: 2 },
      { path: "Research Design > Statistical Tests", title: "Z-test, ANOVA, Regression, Hypothesis Testing", level: 2 },
      { path: "Writing Research Proposal", title: "Writing Research Proposal", level: 1 },
      { path: "Writing Research Proposal > The Problem and Its Background", title: "The Problem and Its Background", level: 2 },
      { path: "Writing Research Proposal > Review of Related Literature", title: "Review of Related Literature", level: 2 },
      { path: "Writing Research Proposal > Research Methods and Procedure", title: "Research Methods and Procedure", level: 2 },
      { path: "Ethical Issues on Research", title: "Ethical Issues on Research", level: 1 },
    ],
  },
  {
    subject_code: "FLUMECH",
    subject_title: "Fluid Mechanics",
    topics: [
      { path: "Introduction", title: "Introduction", level: 1 },
      { path: "Properties of Fluids", title: "Properties of Fluids", level: 1 },
      { path: "Properties of Fluids > Compressible and Incompressible Fluids", title: "Compressible and Incompressible Fluids", level: 2 },
      { path: "Properties of Fluids > Bulk Modulus of Elasticity", title: "Bulk Modulus of Elasticity", level: 2 },
      { path: "Properties of Fluids > Gas Equation of State", title: "Gas Equation of State, Compressibility of Gases", level: 2 },
      { path: "Properties of Fluids > Inviscid and Viscous Fluids", title: "Inviscid and Viscous Fluids, Surface Tension", level: 2 },
      { path: "Fluid Statics", title: "Fluid Statics", level: 1 },
      { path: "Fluid Statics > Pressure Variation in Static Fluid", title: "Pressure Variation in Static Fluid, Absolute and Gage Pressures", level: 2 },
      { path: "Fluid Statics > Pressure Measuring Devices", title: "Pressure Measuring Devices", level: 2 },
      { path: "Fluid Statics > Force on Plane Area and Center of Pressure", title: "Force on Plane Area, Center of Pressure", level: 2 },
      { path: "Fluid Statics > Force on Curved Surface", title: "Force on Curved Surface", level: 2 },
      { path: "Fluid Statics > Buoyancy and Stability", title: "Buoyancy and Stability of Submerged and Floating Bodies", level: 2 },
      { path: "Fluid Statics > Fluid Masses Subjected to Acceleration", title: "Fluid Masses Subjected to Acceleration", level: 2 },
      { path: "Conservation of Energy", title: "Conservation of Energy", level: 1 },
      { path: "Conservation of Energy > Bernoulli's Equation", title: "Equation of Steady Motion along a Streamline for an Ideal Fluid (Bernoulli's Equation) and Real Fluid", level: 2 },
      { path: "Conservation of Energy > Energy Equation for Steady Flow", title: "Energy Equation for Steady Flow of Incompressible Fluids", level: 2 },
      { path: "Conservation of Energy > Cavitation and Hydraulic Grade Line", title: "Cavitation, Hydraulic Grade Line and Energy Line", level: 2 },
      { path: "Conservation of Energy > Vortex Flow", title: "Forced Vortex, Free or Irrotational Vortex", level: 2 },
      { path: "Basic Hydrodynamics", title: "Basic Hydrodynamics", level: 1 },
      { path: "Basic Hydrodynamics > Differential Equation of Continuity", title: "Differential Equation of Continuity", level: 2 },
      { path: "Basic Hydrodynamics > Rotational and Irrotational Flow", title: "Rotational and Irrotational Flow, Circulation and Vorticity", level: 2 },
      { path: "Basic Hydrodynamics > Stream Function and Velocity Potential", title: "Stream Function, Velocity Potential, Orthogonality of Streamlines and Equipotential Lines", level: 2 },
      { path: "Similitude and Dimensional Analysis", title: "Similitude and Dimensional Analysis", level: 1 },
      { path: "Similitude and Dimensional Analysis > Geometric, Kinematic, Dynamic Similarity", title: "Geometric Similarity, Kinematic Similarity, Dynamic Similarity, Scale Ratios", level: 2 },
      { path: "Similitude and Dimensional Analysis > Buckingham PI Theorem", title: "Dimensional Analysis and Buckingham PI Theorem", level: 2 },
      { path: "Momentum and Forces in Fluid Flow", title: "Momentum and Forces in Fluid Flow", level: 1 },
      { path: "Momentum and Forces in Fluid Flow > Impulse-Momentum Principle", title: "Impulse-Momentum Principle", level: 2 },
      { path: "Momentum and Forces in Fluid Flow > Force on Vanes and Blades", title: "Force on Stationary and Moving Vane or Blade", level: 2 },
      { path: "Momentum and Forces in Fluid Flow > Propellers and Windmills", title: "Momentum Principle Applied to Propellers and Windmills", level: 2 },
      { path: "Steady Incompressible Flow in Pressure Conduits", title: "Steady Incompressible Flow in Pressure Conduits", level: 1 },
      { path: "Steady Incompressible Flow in Pressure Conduits > Reynolds Number and Hydraulic Radius", title: "Critical Reynolds Number, Hydraulic Radius", level: 2 },
      { path: "Steady Incompressible Flow in Pressure Conduits > Friction Factor and Losses", title: "Friction Factor, Fluid Friction in Noncircular Conduits, Different Types of Losses", level: 2 },
      { path: "Steady Incompressible Flow in Pressure Conduits > Branching Pipes, Series and Parallel", title: "Branching Pipes, Pipes in Series and Parallel", level: 2 },
      { path: "Fluid Measurements", title: "Fluid Measurements", level: 1 },
      { path: "Fluid Measurements > Venturi Tube, Orifice Meter, Weirs", title: "Measuring Devices: Venturi Tube, Orifice Meter, Weirs", level: 2 },
      { path: "Multi-Phase Flow", title: "Multi-Phase Flow", level: 1 },
    ],
  },
  {
    subject_code: "MACHEL",
    subject_title: "Machine Elements",
    topics: [
      { path: "Introduction to Kinematics of Machineries", title: "Introduction to the Concepts of Kinematics of Machineries", level: 1 },
      { path: "Vector Operations", title: "Vector Operations in Analytical and Graphical Method", level: 1 },
      { path: "Motion and Machinery", title: "Motion and Machinery: Displacement, Velocity and Acceleration, Linkage and Constraints", level: 1 },
      { path: "Instant Center", title: "Instant Center: Location of Instant Center", level: 1 },
      { path: "Velocity Analysis Method", title: "Velocity Analysis Method", level: 1 },
      { path: "Acceleration Analysis", title: "Acceleration Analysis", level: 1 },
      { path: "Cam and Follower", title: "Cam and Follower", level: 1 },
      { path: "Rolling Bodies in Pure Contact", title: "Rolling Bodies in Pure Contact", level: 1 },
      { path: "Gears", title: "Gears", level: 1 },
      { path: "Gear Train", title: "Gear Train", level: 1 },
      { path: "Belts and Pulleys", title: "Belts and Pulleys", level: 1 },
      { path: "Chains", title: "Chains", level: 1 },
      { path: "Flexible Connections", title: "Flexible Connections", level: 1 },
      { path: "Stepped Pulleys", title: "Stepped Pulleys", level: 1 },
    ],
  },
  {
    subject_code: "MATSCI",
    subject_title: "Materials Science and Engineering for ME",
    topics: [
      { path: "Nature of Materials", title: "Nature of Materials", level: 1 },
      { path: "Nature of Materials > Types of Engineering Materials", title: "Types of Engineering Materials", level: 2 },
      { path: "Nature of Materials > Engineering Materials Composition", title: "Engineering Materials Composition", level: 2 },
      { path: "Nature of Materials > Chemical Bonding", title: "Chemical Bonding", level: 2 },
      { path: "Properties and Characteristics of Materials", title: "Properties and Characteristics of Materials", level: 1 },
      { path: "Properties and Characteristics of Materials > Physical Properties", title: "Physical Properties", level: 2 },
      { path: "Properties and Characteristics of Materials > Mechanical Properties", title: "Mechanical Properties", level: 2 },
      { path: "Properties and Characteristics of Materials > Chemical Properties", title: "Chemical Properties", level: 2 },
      { path: "Properties and Characteristics of Materials > Thermal Properties", title: "Thermal Properties", level: 2 },
      { path: "Properties and Characteristics of Materials > Electrical Properties", title: "Electrical Properties", level: 2 },
      { path: "Properties and Characteristics of Materials > Magnetic Properties", title: "Magnetic Properties", level: 2 },
      { path: "Properties and Characteristics of Materials > Optical Properties", title: "Optical Properties", level: 2 },
      { path: "Material Testing", title: "Material Testing", level: 1 },
      { path: "Material Testing > Tension Test", title: "Tension Test", level: 2 },
      { path: "Material Testing > Compression Test", title: "Compression Test", level: 2 },
      { path: "Material Testing > Coefficient of Thermal Expansion", title: "Coefficient of Thermal Expansion", level: 2 },
      { path: "Material Testing > Beam Deflection", title: "Beam Deflection", level: 2 },
      { path: "Material Testing > Shear and Torsion Test", title: "Shear/Torsion Test", level: 2 },
      { path: "Fracture Toughness and Fatigue", title: "Fracture Toughness and Fatigue and Engineering Materials", level: 1 },
      { path: "Fracture Toughness and Fatigue > Impact Testing", title: "Impact Testing", level: 2 },
      { path: "Fracture Toughness and Fatigue > Destructive Testing", title: "Destructive Testing", level: 2 },
      { path: "Fracture Toughness and Fatigue > Fatigue Testing", title: "Fatigue Testing", level: 2 },
      { path: "Corrosion Prevention and Control", title: "Corrosion Prevention and Control", level: 1 },
      { path: "Corrosion Prevention and Control > Electrochemical Nature of Aqueous Corrosion", title: "Electrochemical Nature of Aqueous Corrosion", level: 2 },
      { path: "Corrosion Prevention and Control > Galvanic and Concentration Cell Corrosion", title: "Galvanic and Concentration Cell Corrosion", level: 2 },
      { path: "Non-Destructive Testing", title: "Non-Destructive Testing", level: 1 },
      { path: "Non-Destructive Testing > Magnetic Particle", title: "Magnetic Particle", level: 2 },
      { path: "Non-Destructive Testing > Ultrasonic Testing", title: "Ultrasonic Testing", level: 2 },
      { path: "Non-Destructive Testing > Penetrant Testing", title: "Penetrant Testing", level: 2 },
      { path: "Non-Destructive Testing > Radiographic Testing", title: "Radiographic Testing", level: 2 },
      { path: "Ferrous and Non-ferrous Metals", title: "Ferrous and Non-ferrous Metals", level: 1 },
      { path: "Ceramics", title: "Ceramics", level: 1 },
      { path: "Polymers", title: "Polymers", level: 1 },
      { path: "Composite Materials", title: "Composite Materials", level: 1 },
      { path: "Nano and Bio Materials", title: "Nano and Bio Materials", level: 1 },
      { path: "Selection, Re-use and Recycling of Materials", title: "Selection, Re-use and Recycling of Materials", level: 1 },
    ],
  },
  {
    subject_code: "THERMO1",
    subject_title: "Thermodynamics 1",
    topics: [
      { path: "Introduction", title: "Introduction", level: 1 },
      { path: "Basic Principles, Concepts and Definitions", title: "Basic Principles, Concepts and Definitions", level: 1 },
      { path: "First Law of Thermodynamics", title: "First Law of Thermodynamics", level: 1 },
      { path: "Ideal Gases and Ideal Gas Laws", title: "Ideal Gases/Ideal Gas Laws", level: 1 },
      { path: "Processes of Ideal Gases", title: "Processes of Ideal Gases", level: 1 },
      { path: "Properties of Pure Substance", title: "Properties of Pure Substance", level: 1 },
      { path: "Processes of Pure Substance", title: "Processes of Pure Substance", level: 1 },
      { path: "Second Law of Thermodynamics", title: "Introduction to Cycle Analysis: Second Law of Thermodynamics", level: 1 },
      { path: "Introduction to Gas and Vapor Cycles", title: "Introduction to Gas and Vapor Cycles", level: 1 },
      { path: "Real Gases", title: "Real Gases", level: 1 },
    ],
  },
  {
    subject_code: "THERMO2",
    subject_title: "Thermodynamics 2",
    topics: [
      { path: "Review of Thermodynamic Cycle", title: "Review the Thermodynamic Cycle", level: 1 },
      { path: "Simple Rankine Cycle Analysis", title: "Simple Rankine Cycle Analysis", level: 1 },
      { path: "Improving Rankine Cycle Efficiency", title: "Improving Rankine Cycle Efficiency", level: 1 },
      { path: "Actual Rankine Cycle", title: "Actual Rankine Cycle", level: 1 },
      { path: "Ideal and Actual Reheat Cycle", title: "Ideal and Actual Reheat Cycle", level: 1 },
      { path: "Ideal and Actual Regenerative Cycle", title: "Ideal and Actual Regenerative Cycle", level: 1 },
      { path: "Ideal and Actual Reheat-Regenerative Cycle", title: "Ideal and Actual Reheat-Regenerative Cycle", level: 1 },
      { path: "Binary Cycles", title: "Binary Cycles", level: 1 },
      { path: "Topping or Superposing Cycles", title: "Topping or Superposing Cycles", level: 1 },
      { path: "Incomplete Expansion Engine", title: "Incomplete Expansion Engine", level: 1 },
      { path: "Other Gas Power Cycles", title: "Other Gas Power Cycles", level: 1 },
      { path: "Other Gas Power Cycles > Brayton Cycle", title: "Brayton Cycle", level: 2 },
      { path: "Other Gas Power Cycles > Air-Standard Cycle OTTO/Diesel", title: "Air-Standard Cycle, OTTO/Diesel Cycle", level: 2 },
      { path: "Gas Compression Analysis", title: "Gas Compression Analysis", level: 1 },
      { path: "Real Gases", title: "Real Gases", level: 1 },
      { path: "Properties of Gas and Vapor Mixtures", title: "Properties of Gas and Vapor Mixtures", level: 1 },
    ],
  },
  {
    subject_code: "COMBENG",
    subject_title: "Combustion Engineering",
    topics: [
      { path: "Introduction", title: "Introduction", level: 1 },
      { path: "Principles of Thermodynamics", title: "Principles of Thermodynamics", level: 1 },
      { path: "Mixture of Gases", title: "Mixture of Gases", level: 1 },
      { path: "Theoretical Cycles", title: "Theoretical Cycles", level: 1 },
      { path: "Handling of Gaseous Fuels", title: "Handling of Gaseous Fuels", level: 1 },
      { path: "Handling of Volatile Liquid Fuels", title: "Handling of Volatile Liquid Fuels", level: 1 },
      { path: "Handling of Fuel Oils", title: "Handling of Fuel Oils", level: 1 },
      { path: "Engine Testing and Performance", title: "Engine Testing and Performance", level: 1 },
      { path: "Engine Design", title: "Engine Design", level: 1 },
      { path: "External Combustion", title: "External Combustion", level: 1 },
      { path: "Combustion of Fuels", title: "Combustion of Fuels", level: 1 },
    ],
  },
  {
    subject_code: "HEATXFER",
    subject_title: "Heat Transfer",
    topics: [
      { path: "Overview of Heat Transfer", title: "Overview of Heat Transfer, Modes of Heat Transfer, Definitions, Differences and Applications", level: 1 },
      { path: "Conduction: Steady-State", title: "Conduction: Steady-State Conduction of Plane Wall and Radial System", level: 1 },
      { path: "Conduction with Film Coefficient", title: "Conduction with Film Coefficient of Convection", level: 1 },
      { path: "Free Convection", title: "Free Convection: Vertical Plates, Inclined and Horizontal Plates, Cylinders/Tubes, Spheres", level: 1 },
      { path: "Forced Convection", title: "Forced Convection: Pipe and Tubes, Cylinders and Spheres, Tube Banks", level: 1 },
      { path: "Radiation: Processes and Properties", title: "Radiation: Processes and Properties", level: 1 },
      { path: "Radiation Exchange between Surfaces", title: "Radiation Exchange between Surfaces: View Factor, Blackbody Radiation, Gray Surfaces", level: 1 },
      { path: "Multi-Mode Heat Transfer", title: "Multi-Mode Heat Transfer: Combination of Two Modes or All Modes", level: 1 },
      { path: "Heat Exchangers", title: "Heat Exchangers", level: 1 },
      { path: "Heat Exchangers > Types and Overall Heat Transfer Coefficient", title: "Types, Overall Heat Transfer Coefficient", level: 2 },
      { path: "Heat Exchangers > LMTD and AMTD", title: "LMTD and AMTD", level: 2 },
      { path: "Heat Exchangers > Parallel Flow and Counter Flow", title: "Parallel Flow and Counter Flow", level: 2 },
      { path: "Heat Exchangers > Multi-Pass and Cross Flow", title: "Multi-Pass and Cross Flow", level: 2 },
    ],
  },
  {
    subject_code: "MELAB1",
    subject_title: "ME Laboratory 1",
    topics: [
      { path: "Density, Specific Gravity and Viscosity of Liquid Fuels", title: "Determination of Density, Specific Gravity and Viscosity of Liquid Fuels", level: 1 },
      { path: "Flash and Fire Points", title: "Flash and Fire Points of Liquid Fuels and Grease", level: 1 },
      { path: "Drop and Hardness Tests of Greases", title: "Drop and Hardness Tests of Greases", level: 1 },
      { path: "Carbon Residue Test", title: "Carbon Residue Test", level: 1 },
      { path: "Test of Solid Fuel", title: "Test of Solid Fuel", level: 1 },
      { path: "Calorific Test of Gaseous Fuel", title: "Calorific Test of Gaseous Fuel", level: 1 },
      { path: "Flue Gas Analysis", title: "Flue Gas Analysis", level: 1 },
      { path: "Water and Sediments Test", title: "Water and Sediments Test", level: 1 },
      { path: "Cloud and Pour Points Test", title: "Cloud and Pour Points Test", level: 1 },
      { path: "Distillation and Vapor Pressure Tests of Gasoline Fuel", title: "Distillation and Vapor Pressure Tests of Gasoline Fuel", level: 1 },
      { path: "Calibration of Pressure and Temperature Measuring Instruments", title: "Calibration and Use of Pressure and Temperature Measuring Instruments", level: 1 },
      { path: "Measurement of Length, Areas, Speed and Time", title: "Measurement of Length, Areas, Speed and Time", level: 1 },
      { path: "Calibration of Platform Scale", title: "Calibration of Platform Scale", level: 1 },
      { path: "Calibration of Volume Tank and Flow Instruments", title: "Calibration of Volume Tank, Water Meter, Orifice, Venturi Meter and Weir", level: 1 },
      { path: "Measurement of Humidity", title: "Measurement of Humidity", level: 1 },
      { path: "Static, Velocity and Total Pressure Measurement", title: "Determination of Static, Velocity and Total Pressure Using Manometers and Pitot Tube", level: 1 },
      { path: "Dynamometer and Power Measurement", title: "Dynamometer and Power Measurement", level: 1 },
    ],
  },
  {
    subject_code: "MELAB2",
    subject_title: "ME Laboratory 2",
    topics: [
      { path: "Physical Study of the Steam Generating Unit", title: "Physical Study of the Steam Generating Unit", level: 1 },
      { path: "Test of Centrifugal Fan and Rotary Blower", title: "Test of Centrifugal Fan and Rotary Blower", level: 1 },
      { path: "Test of an Air Compressor", title: "Test of an Air Compressor", level: 1 },
      { path: "Measurement of Steam Quality", title: "Measurement of a Steam Quality", level: 1 },
      { path: "Heat Loss through Pipes", title: "Heat Loss Calculation through Bare and Lagged Pipes", level: 1 },
      { path: "Test of Parallel and Counter Flow Heat Exchangers", title: "Test of Parallel and Counter Flow Heat Exchangers", level: 1 },
      { path: "Test of a Surface Condenser", title: "Test of a Surface Condenser", level: 1 },
      { path: "Test of a Tubular Condenser", title: "Test of a Tubular Condenser", level: 1 },
      { path: "Visualization of Fluid Flow using Reynolds Number", title: "Visualization of Fluid Flow using Reynolds Number Apparatus", level: 1 },
      { path: "Performance Test of an Internal Combustion Engine", title: "Performance Test of an Internal Combustion Engine", level: 1 },
      { path: "Test of Series and Parallel Pump Flow", title: "Test of a Series and Parallel Pump Flow", level: 1 },
      { path: "Performance Test of a Positive Displacement Pump", title: "Performance Test of a Positive Displacement Pump", level: 1 },
      { path: "Performance Test of a Non-Positive Displacement Pump", title: "Performance Test of a Non-Positive Displacement Pump", level: 1 },
      { path: "Performance Test of a Hydraulic Turbine", title: "Performance Test of a Hydraulic Turbine", level: 1 },
    ],
  },
  {
    subject_code: "MANFIND",
    subject_title: "Manufacturing and Industrial Processes with Plant Visits",
    topics: [
      { path: "Handling of Solids", title: "Methods, Processes and Equipment Involved in Handling of Solids", level: 1 },
      { path: "Handling of Solids > Feeders and Storage Silos", title: "Feeders and Storage Silos", level: 2 },
      { path: "Handling of Solids > Conveyors and Conveying Systems", title: "Conveyors and Conveying Systems", level: 2 },
      { path: "Handling of Solids > Size Reduction of Solids", title: "Size Reduction of Solids", level: 2 },
      { path: "Handling of Solids > Separation and Classification of Solids", title: "Separation and Classification of Solids", level: 2 },
      { path: "Dryers and Drying Processes", title: "Dryers and Drying Processes", level: 1 },
      { path: "Manufacturing Processes", title: "Methods, Processes and Equipment Involved in Manufacturing", level: 1 },
      { path: "Manufacturing Processes > Cement", title: "Cement Manufacturing", level: 2 },
      { path: "Manufacturing Processes > Steel", title: "Steel Manufacturing", level: 2 },
      { path: "Manufacturing Processes > Glass", title: "Glass Manufacturing", level: 2 },
      { path: "Manufacturing Processes > Plastic and Rubber", title: "Plastic and Rubber Manufacturing", level: 2 },
      { path: "Manufacturing Processes > Food and Beverage", title: "Food and Beverage Manufacturing", level: 2 },
      { path: "Manufacturing Processes > Electronics and Semiconductors", title: "Electronics and Semiconductor Manufacturing", level: 2 },
      { path: "Manufacturing Processes > Metals", title: "Metals Manufacturing", level: 2 },
      { path: "Packaging Processes and Equipment", title: "Packaging Processes and Equipment", level: 1 },
      { path: "Plant Visits", title: "Plant Visits to Manufacturing and Industrial Plants", level: 1 },
      { path: "Plumbing", title: "Plumbing", level: 1 },
    ],
  },
  {
    subject_code: "BOSH",
    subject_title: "Basic Occupational Safety and Health",
    topics: [
      { path: "Introductory Concepts", title: "Introductory Concepts: Promoting Safety and Health as an Engineer's Professional and Ethical Responsibility", level: 1 },
      { path: "Occupational Safety", title: "Occupational Safety", level: 1 },
      { path: "Industrial Hygiene", title: "Industrial Hygiene", level: 1 },
      { path: "Control Measures for OSH Hazards", title: "Control Measures for OSH Hazards", level: 1 },
      { path: "Occupational Health", title: "Occupational Health", level: 1 },
      { path: "Personal Protective Equipment", title: "Personal Protective Equipment", level: 1 },
      { path: "OSH Programming", title: "OSH Programming", level: 1 },
      { path: "Training of Personnel on OSH", title: "Training of Personnel on OSH", level: 1 },
      { path: "OSH Legislation", title: "OSH Legislation", level: 1 },
      { path: "Plant Visit Simulation", title: "Plant Visit Simulation", level: 1 },
      { path: "Fire Protection", title: "Fire Protection", level: 1 },
    ],
  },
  {
    subject_code: "WKSTP",
    subject_title: "Workshop Theory and Practice",
    topics: [
      { path: "Introduction to Machine Shop Operations", title: "Introduction to Machine Shop Operations, Layouts, Tools and Measuring Instruments", level: 1 },
      { path: "Machine Shop Safety, Rules and Regulations", title: "Machine Shop Safety, Rules and Regulations", level: 1 },
      { path: "Metal Working Processes", title: "Metal Working Processes", level: 1 },
      { path: "Familiarization on Machine Tools and Equipment", title: "Familiarization on the Use of Machine Tools and Equipment", level: 1 },
      { path: "Familiarization on Machine Tools and Equipment > Caliper", title: "Caliper", level: 2 },
      { path: "Familiarization on Machine Tools and Equipment > Ball Peen Hammer", title: "Ball Peen Hammer", level: 2 },
      { path: "Familiarization on Machine Tools and Equipment > Drilling and Grinding Machines", title: "Drilling and Grinding Machines", level: 2 },
      { path: "Familiarization on Machine Tools and Equipment > Lathe Machines", title: "Lathe Machines", level: 2 },
      { path: "Familiarization on Machine Tools and Equipment > Shaper and Milling Machines", title: "Shaper and Milling Machines", level: 2 },
      { path: "Familiarization on Machine Tools and Equipment > Welding Machines", title: "Welding Machines", level: 2 },
      { path: "Familiarization on Machine Tools and Equipment > Forge and Foundry Equipment", title: "Forge and Foundry Equipment", level: 2 },
    ],
  },
  {
    subject_code: "MSHOP",
    subject_title: "Machine Shop Theory",
    topics: [
      { path: "Principles of Machine Shop Practices", title: "Principles of Machine Shop Practices", level: 1 },
      { path: "Classification, Applications and Operations of Machines", title: "Classification, Applications and Operations of Machines", level: 1 },
      { path: "New Technologies and Trends in Machine Shop Operations", title: "New Technologies and Trends in Machine Shop Operations", level: 1 },
      { path: "Practical Exercises and Projects", title: "Practical Exercises and Projects Using the Different Types of Machines", level: 1 },
      { path: "Introduction to Numerical Controlled Machines and Automation", title: "Introduction to Numerical Controlled Machines and Automation", level: 1 },
    ],
  },
  {
    subject_code: "CTRLENG",
    subject_title: "Control Engineering",
    topics: [
      { path: "Introduction to Control Systems", title: "Introduction to Control Systems. Open-loop Control. Closed-loop Control", level: 1 },
      { path: "Laplace Transforms", title: "Laplace Transforms", level: 1 },
      { path: "Transfer Functions", title: "Transfer Functions", level: 1 },
      { path: "Block Diagrams and Signal Flow Graphs", title: "Block Diagrams and Signal Flow Graphs", level: 1 },
      { path: "Physical Systems Modeling", title: "Physical Systems Modeling", level: 1 },
      { path: "System Stability", title: "System Stability", level: 1 },
      { path: "Root Locus Analysis", title: "Root Locus Analysis", level: 1 },
      { path: "Time Domain Analysis", title: "Time Domain Analysis of Control Systems", level: 1 },
      { path: "Frequency Domain Analysis", title: "Frequency Domain Analysis of Control Systems", level: 1 },
      { path: "Control System Design", title: "Control System Design. Classical Control Techniques. PID Controllers", level: 1 },
      { path: "Introduction to Digital Control", title: "Introduction to Digital Control. The z-Transform", level: 1 },
      { path: "Computer Programming Exercises", title: "Computer Programming Exercises and Examples", level: 1 },
      { path: "Laboratory Exercises", title: "Laboratory Exercises", level: 1 },
    ],
  },
  {
    subject_code: "FLUMACH",
    subject_title: "Fluid Machineries",
    topics: [
      { path: "Definitions and Terminologies", title: "Definitions and Terminologies", level: 1 },
      { path: "Dimensional Analysis Applied to Fluid Machineries", title: "Dimensional Analysis as Applied to Fluid Machineries", level: 1 },
      { path: "Specific Speed of Fluid Machineries", title: "Specific Speed of Fluid Machineries", level: 1 },
      { path: "Basic Pump Construction", title: "Basic Pump Construction (Impellers, Diffusers, etc.)", level: 1 },
      { path: "Net Positive Suction Head and Cavitation", title: "Net Positive Suction Head and Cavitation", level: 1 },
      { path: "Pump Operation, Pipe Sizing and Selection", title: "Pump Operation, Pipe Sizing and Selection", level: 1 },
      { path: "Axial and Centrifugal Pumps, Fans and Blowers", title: "Axial and Centrifugal Pumps, Fans and Blowers", level: 1 },
      { path: "Basic Turbine Construction", title: "Basic Turbine Construction (Blades, Diffuser, etc.)", level: 1 },
      { path: "Impulse and Reaction Turbines", title: "Impulse and Reaction Turbines", level: 1 },
      { path: "Sizing and Selection of Turbines", title: "Sizing and Selection of Turbines", level: 1 },
      { path: "Applications of Fluid Machineries", title: "Applications of Fluid Machineries", level: 1 },
    ],
  },
  {
    subject_code: "REFSYS",
    subject_title: "Refrigeration Systems",
    topics: [
      { path: "Introduction to Refrigeration System", title: "Introduction to Refrigeration System", level: 1 },
      { path: "Refrigerants", title: "Refrigerants", level: 1 },
      { path: "Standard and Actual Vapor Compression Cycle", title: "Standard and Actual Vapor Compression Cycle", level: 1 },
      { path: "Functions and Performance of Compressors", title: "Functions and Performance of Compressors", level: 1 },
      { path: "Functions and Performance of Evaporators", title: "Functions and Performance of Evaporators", level: 1 },
      { path: "Functions and Performance of Condensers", title: "Functions and Performance of Condensers", level: 1 },
      { path: "Functions and Performance of Expansion Devices", title: "Functions and Performance of Expansion Devices", level: 1 },
      { path: "Multi-Stage Refrigeration System", title: "Multi-Stage Refrigeration System", level: 1 },
      { path: "Absorption Refrigeration Cycle", title: "Absorption Refrigeration Cycle", level: 1 },
      { path: "Air Cycle Refrigeration System", title: "Air Cycle Refrigeration System", level: 1 },
      { path: "Steam Jet Refrigeration Cycle", title: "Steam Jet Refrigeration Cycle", level: 1 },
      { path: "Special Topics in Refrigeration Systems", title: "Special Topics in Refrigeration Systems (Thermoacoustics, Thermoelectric, Cryogenics, Solar Powered)", level: 1 },
    ],
  },
  {
    subject_code: "ACVSYS",
    subject_title: "Air Conditioning and Ventilation Systems",
    topics: [
      { path: "Air-Conditioning System and Psychrometric Processes", title: "Air-Conditioning System and Its Psychrometric Processes and Application", level: 1 },
      { path: "Air-Conditioning Processes", title: "Air-Conditioning Processes", level: 1 },
      { path: "Cooling Towers and Air Dryers", title: "Cooling Towers and Air Dryers", level: 1 },
      { path: "Cooling Load Calculations", title: "Cooling Load Calculations", level: 1 },
      { path: "Air Distribution System and Duct Sizing", title: "Air Distribution System, Duct Sizing and Equipment Specification", level: 1 },
      { path: "Refrigerant Piping and Chilled Water Systems", title: "Refrigerant Piping, Chilled and Cooling Water Piping System, Air Conditioning Equipment Design and Selection", level: 1 },
      { path: "Ventilation", title: "Ventilation", level: 1 },
      { path: "Comfort Condition and Indoor Air Quality", title: "Comfort Condition and Indoor Air Quality", level: 1 },
      { path: "Energy Efficient Buildings Standards", title: "Introduction to 2010 PSVARE Standard for Energy Efficient Buildings", level: 1 },
      { path: "Conventional and Alternative Air-Conditioning Systems", title: "Conventional and Alternative Air-Conditioning Systems", level: 1 },
    ],
  },
  {
    subject_code: "VIBENG",
    subject_title: "Vibration Engineering",
    topics: [
      { path: "Basic Concepts of Vibrating System", title: "Basic Concepts of Vibrating System", level: 1 },
      { path: "Basic Concepts of Vibrating System > Equivalent Solutions", title: "Equivalent Solutions", level: 2 },
      { path: "Basic Concepts of Vibrating System > Equivalent Users", title: "Equivalent Users", level: 2 },
      { path: "Basic Concepts of Vibrating System > Equivalent Damping", title: "Equivalent Damping", level: 2 },
      { path: "Free Vibration", title: "Free Vibration", level: 1 },
      { path: "Free Vibration > Harmonic Motion", title: "Harmonic Motion", level: 2 },
      { path: "Free Vibration > Viscous Damping", title: "Viscous Damping", level: 2 },
      { path: "Free Vibration > Design Considerations", title: "Design Considerations", level: 2 },
      { path: "Free Vibration > Stability", title: "Stability", level: 2 },
      { path: "Harmonically Excited Vibration", title: "Harmonically Excited Vibration", level: 1 },
      { path: "Harmonically Excited Vibration > Equation of Motion", title: "Equation of Motion", level: 2 },
      { path: "Harmonically Excited Vibration > Response of an Undamped System", title: "Response of an Undamped System", level: 2 },
      { path: "Harmonically Excited Vibration > Response of a Damped System", title: "Response of a Damped System", level: 2 },
      { path: "Vibration under General Forcing Conditions", title: "Vibration under General Forcing Conditions", level: 1 },
      { path: "Vibration under General Forcing Conditions > Response under General Periodic Force", title: "Response under a General Periodic Force", level: 2 },
      { path: "Vibration under General Forcing Conditions > Response under Non-Periodic Force", title: "Response under Non-Periodic Force", level: 2 },
      { path: "Vibration Measurement", title: "Vibration Measurement", level: 1 },
      { path: "Vibration Analysis and Control", title: "Vibration Analysis and Control", level: 1 },
    ],
  },
  // ============================================================
  // F. PROFESSIONAL MECHANICAL ENGINEERING COURSES
  // ============================================================
  {
    subject_code: "MACHDES1",
    subject_title: "Machine Design 1",
    topics: [
      { path: "Analysis of Simple Stresses", title: "Analysis of Simple Stresses", level: 1 },
      { path: "Analysis of Simple Stresses > Tensile", title: "Tensile Stress", level: 2 },
      { path: "Analysis of Simple Stresses > Compressive", title: "Compressive Stress", level: 2 },
      { path: "Analysis of Simple Stresses > Shear or Torsion", title: "Shear or Torsion", level: 2 },
      { path: "Analysis of Simple Stresses > Bending or Flexural", title: "Bending or Flexural", level: 2 },
      { path: "Tolerance and Allowances", title: "Tolerance and Allowances", level: 1 },
      { path: "Tolerance and Allowances > Tolerances", title: "Tolerances", level: 2 },
      { path: "Tolerance and Allowances > Allowances", title: "Allowances", level: 2 },
      { path: "Variable Stress Analysis", title: "Variable Stress Analysis", level: 1 },
      { path: "Variable Stress Analysis > With Stress Concentration", title: "With Stress Concentration", level: 2 },
      { path: "Variable Stress Analysis > Without Stress Concentration", title: "Without Stress Concentration", level: 2 },
      { path: "Variable Stress Analysis > Definite Life Design", title: "Definite Life Design", level: 2 },
      { path: "Variable Stress Analysis > Indefinite Life Design", title: "Indefinite Life Design", level: 2 },
      { path: "Shaft Design", title: "Shaft Design", level: 1 },
      { path: "Shaft Design > Pure Bending", title: "Pure Bending", level: 2 },
      { path: "Shaft Design > Pure Torsion", title: "Pure Torsion", level: 2 },
      { path: "Shaft Design > Combined Loads", title: "Combined Loads (Torsion, Bending, Axial)", level: 2 },
      { path: "Shaft Design > Shaft Design Using Codes", title: "Shaft Design Using Codes (PSME, ASME)", level: 2 },
      { path: "Keys and Coupling Design", title: "Keys and Coupling Design", level: 1 },
      { path: "Keys and Coupling Design > Flat and Square Keys", title: "Flat and Square Keys", level: 2 },
      { path: "Keys and Coupling Design > Flexible Coupling", title: "Flexible Coupling", level: 2 },
      { path: "Design of Screw Fastening", title: "Design of Screw Fastening", level: 1 },
      { path: "Design of Screw Fastening > Types of Bolts and Screws", title: "Types of Bolts and Screws", level: 2 },
      { path: "Design of Screw Fastening > Initial Tension and Tightening Torque", title: "Initial Tension and Tightening Torque", level: 2 },
      { path: "Design of Screw Fastening > Bolts and Screws in Shear", title: "Bolts and Screws in Shear", level: 2 },
      { path: "Design of Mechanical Springs", title: "Design of Mechanical Springs", level: 1 },
      { path: "Design of Mechanical Springs > Coil and Leaf Springs", title: "Coil and Leaf Springs Elements", level: 2 },
      { path: "Design of Power Screws", title: "Design of Power Screws", level: 1 },
      { path: "Design of Power Screws > Square Thread", title: "Square Thread", level: 2 },
      { path: "Design of Power Screws > Acme Thread", title: "Acme Thread", level: 2 },
      { path: "Design of Power Screws > Buttress Thread", title: "Buttress Thread", level: 2 },
      { path: "Gears", title: "Gears", level: 1 },
    ],
  },
  {
    subject_code: "MACHDES2",
    subject_title: "Machine Design 2",
    topics: [
      { path: "Flywheels", title: "Flywheels", level: 1 },
      { path: "Brakes and Clutches", title: "Brakes and Clutches", level: 1 },
      { path: "Bearings", title: "Bearings", level: 1 },
      { path: "Flexible Power Transmissions", title: "Flexible Power Transmissions (Belts, Wire Ropes and Chains)", level: 1 },
      { path: "Analysis and Synthesis of Machineries", title: "Analysis and Synthesis of Machineries", level: 1 },
    ],
  },
  {
    subject_code: "MELAB3",
    subject_title: "ME Laboratory 3",
    topics: [
      { path: "Performance Test of a Simple Steam Power Plant", title: "Performance, Heat Balance and Efficiency Test of a Simple Steam Power Plant", level: 1 },
      { path: "Performance Test of a Diesel Electric Power Plant", title: "Performance, Heat Balance and Efficiency Test of a Diesel Electric Power Plant", level: 1 },
      { path: "Performance Test of a Mini-Hydroelectric Power Plant", title: "Performance Test of a Mini-Hydroelectric Power Plant", level: 1 },
      { path: "Performance and Efficiency Test of a Refrigeration Plant", title: "Performance and Efficiency Test of a Refrigeration Plant", level: 1 },
      { path: "Performance and Efficiency Test of an Air Conditioning Plant", title: "Performance and Efficiency Test of an Air Conditioning Plant", level: 1 },
    ],
  },
  {
    subject_code: "INDPLANT",
    subject_title: "Industrial Plant Engineering",
    topics: [
      { path: "Basic Design Concepts of Industrial Plant Systems", title: "Basic Design Concepts of Industrial Plant Systems and Equipment", level: 1 },
      { path: "General Piping Systems and Layouts", title: "General Piping Systems and Layouts of Industrial Plants", level: 1 },
      { path: "Principles of Materials Handling", title: "Principles of Materials Handling", level: 1 },
      { path: "Industrial Steam Processes", title: "Industrial Steam Processes", level: 1 },
      { path: "Industrial Waste Water Treatment", title: "Industrial Waste Water Treatment", level: 1 },
      { path: "Air Pollution Control Systems", title: "Air Pollution Control Systems for Industrial Application", level: 1 },
      { path: "Fire Protection System", title: "Fire Protection System", level: 1 },
    ],
  },
  {
    subject_code: "POWERPLANT",
    subject_title: "Power Plant Design with Renewable Energy",
    topics: [
      { path: "Steam Power Plants", title: "Steam Power Plants", level: 1 },
      { path: "Variable Load Problems", title: "Variable Load Problems", level: 1 },
      { path: "Diesel Electric Power Plants", title: "Diesel Electric Power Plants", level: 1 },
      { path: "Gas Turbine Power Plants", title: "Gas Turbine Power Plants", level: 1 },
      { path: "Hydro-electric Power Plants", title: "Hydro-electric Power Plants", level: 1 },
      { path: "Geothermal Power Plants", title: "Geothermal Power Plants", level: 1 },
      { path: "Combined Cycle Power Plants", title: "Combined Cycle Power Plants", level: 1 },
      { path: "Renewable Energies", title: "Renewable Energies: Solar, Wind, Tidal, Hydro-electric, Bio-mass, OTEC and Others", level: 1 },
      { path: "Power Plant Economics", title: "Power Plant Economics", level: 1 },
      { path: "Power Plant Economics > Cost Components in Power Generation", title: "Various Cost Components in Power Generation", level: 2 },
      { path: "Power Plant Economics > Pie Chart Analysis", title: "Pie Chart Analysis and Construction", level: 2 },
      { path: "Power Plant Economics > Plant Cost Comparison", title: "Plant Cost Comparison of Various Types of Power Plants", level: 2 },
      { path: "Co-generation and Energy Management System", title: "Co-generation and Energy Management System", level: 1 },
    ],
  },
  {
    subject_code: "MELAW",
    subject_title: "ME Law, Ethics, Contract, Codes and Standards",
    topics: [
      { path: "The Mechanical Engineering Profession", title: "The Mechanical Engineering Profession", level: 1 },
      { path: "The Mechanical Engineer in Society", title: "The Mechanical Engineer in Society", level: 1 },
      { path: "Mechanical Engineering Law", title: "Mechanical Engineering Law", level: 1 },
      { path: "The Mechanical Engineer's Code of Ethics", title: "The Mechanical Engineer's Code of Ethics", level: 1 },
      { path: "Ethical Issues and Case Studies", title: "Ethical Issues and Case Studies in Engineering", level: 1 },
      { path: "Local and International Codes and Standards", title: "Local and International Codes and Standards", level: 1 },
      { path: "Contracts and Specifications", title: "Contracts and Specifications", level: 1 },
      { path: "National Building Code of the Philippines", title: "National Building Code of the Philippines", level: 1 },
    ],
  },
  {
    subject_code: "MEPROS1",
    subject_title: "ME Project Study 1",
    topics: [
      { path: "Problem Statement and Objectives", title: "Statement of the Problem and Objectives", level: 1 },
      { path: "Significance, Scope and Limitations", title: "Significance of the Study, Scope and Limitations", level: 1 },
      { path: "Review of Related Literature", title: "Review of Related Literature", level: 1 },
      { path: "Underlying Theories and Concepts", title: "Underlying Theories and Concepts", level: 1 },
      { path: "Methodology", title: "Methodology", level: 1 },
      { path: "Project Proposal Oral Presentation", title: "Oral Presentation of Project Study Proposal to a Panel", level: 1 },
    ],
  },
  {
    subject_code: "MEPROS2",
    subject_title: "ME Project Study 2",
    topics: [
      { path: "Problem Statement and Objectives", title: "Statement of the Problem and Objectives", level: 1 },
      { path: "Significance, Scope and Limitations", title: "Significance of the Study, Scope and Limitations", level: 1 },
      { path: "Review of Related Literature", title: "Review of Related Literature", level: 1 },
      { path: "Underlying Theories and Concepts", title: "Underlying Theories and Concepts", level: 1 },
      { path: "Methodology and Data Analysis", title: "Methodology and Data Analysis", level: 1 },
      { path: "Presentation of Results", title: "Presentation of Results", level: 1 },
      { path: "Conclusions and Recommendations", title: "Conclusions and Recommendations", level: 1 },
      { path: "Final Oral Presentation", title: "Oral Presentation of Project Study to a Panel", level: 1 },
    ],
  },
]

async function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

async function embedBatch(texts: string[]): Promise<number[][]> {
  const response = await openai.embeddings.create({
    model: "text-embedding-3-small",
    input: texts,
  })
  return response.data.map((d) => d.embedding)
}

async function main(): Promise<void> {
  console.log("Starting CMO-97-2017 topic seed...")
  console.log(`Total subjects: ${SUBJECTS.length}`)

  // Delete existing rows for this curriculum
  console.log(`\nDeleting existing rows with curriculum_code = '${CURRICULUM_CODE}'...`)
  const { error: deleteError } = await supabase
    .from("cmo_topic_chunks")
    .delete()
    .eq("curriculum_code", CURRICULUM_CODE)
  if (deleteError) {
    console.error("Error deleting existing rows:", deleteError)
    process.exit(1)
  }
  console.log("Deleted existing rows.")

  // Build all rows
  type TopicRow = {
    subject_code: string
    subject_title: string
    curriculum_code: string
    topic_path: string
    topic_title: string
    level: number
    full_context: string
    embedding: number[]
  }

  const allRows: Omit<TopicRow, "embedding">[] = []

  for (const subject of SUBJECTS) {
    for (const topic of subject.topics) {
      const full_context = `${subject.subject_title} > ${topic.path}: ${topic.title}`
      allRows.push({
        subject_code: subject.subject_code,
        subject_title: subject.subject_title,
        curriculum_code: CURRICULUM_CODE,
        topic_path: topic.path,
        topic_title: topic.title,
        level: topic.level,
        full_context,
      })
    }
  }

  console.log(`\nTotal topic rows to embed and insert: ${allRows.length}`)

  // Batch embed with 500ms delay between batches of 20
  const BATCH_SIZE = 20
  const embeddedRows: TopicRow[] = []

  for (let i = 0; i < allRows.length; i += BATCH_SIZE) {
    const batch = allRows.slice(i, i + BATCH_SIZE)
    const batchNum = Math.floor(i / BATCH_SIZE) + 1
    const totalBatches = Math.ceil(allRows.length / BATCH_SIZE)

    console.log(`Embedding batch ${batchNum}/${totalBatches} (rows ${i + 1}-${Math.min(i + BATCH_SIZE, allRows.length)})...`)

    const embeddings = await embedBatch(batch.map((r) => r.full_context))

    for (let j = 0; j < batch.length; j++) {
      embeddedRows.push({ ...batch[j], embedding: embeddings[j] })
    }

    if (i + BATCH_SIZE < allRows.length) {
      await sleep(500)
    }
  }

  console.log(`\nInserting ${embeddedRows.length} rows into cmo_topic_chunks...`)

  // Insert in batches of 100
  const INSERT_BATCH = 100
  for (let i = 0; i < embeddedRows.length; i += INSERT_BATCH) {
    const batch = embeddedRows.slice(i, i + INSERT_BATCH)
    const { error: insertError } = await supabase.from("cmo_topic_chunks").insert(batch)
    if (insertError) {
      console.error(`Error inserting rows ${i + 1}-${i + batch.length}:`, insertError)
      process.exit(1)
    }
    console.log(`  Inserted rows ${i + 1}-${Math.min(i + INSERT_BATCH, embeddedRows.length)}`)
  }

  console.log(`\nSeed complete! Inserted ${embeddedRows.length} topic chunks for ${SUBJECTS.length} subjects.`)
}

main().catch((err) => {
  console.error("Fatal error:", err)
  process.exit(1)
})
